### ISSUE TITLE
20 microseconds

### ISSUE THREAD

**Issue by quantrpeter** [chris-torrence/arduino-at28c64#1]
hi
   I saw you sleep 20 microseconds on write, but based on AT28c16 spec, you should keep WE to low between 100ns and 1000ns. So why your code work? thanks

    digitalLow(AT28_WE_Pin);
    delayMicroseconds(20);
    digitalHigh(AT28_WE_Pin);

<img width="758" alt="Screenshot 2023-09-12 at 12 23 44 AM" src="https://github.com/ct6502/arduino-at28c64/assets/50471577/fcad1e18-88e5-448e-ba5e-eb3718262c8f">

**Comment by ct6502** [comment]
That is an excellent question. It's been a while but I recall having trouble with getting that delay to work properly. It seemed like some chips wanted a longer delay. Perhaps they were "cheap" chips that didn't really follow the spec. Anyway, that 20ms delay seemed to work so I just left it alone. If you run into issues you might try changing it or removing it entirely. I guess I'll close the issue since it worked fine for me but feel free to add more comments if you do some testing and discover issues. Thanks and best of luck!
